### ISSUE TITLE
CPR Limbo

### ISSUE THREAD

**Issue by Stainess** [Pergor/ADV_Medical#28]
Our unit plays older decades where combat medics don't have defibs. 

The ADV setting "Maximum Time for successful CPR" (default 1200 seconds) is pinned to the Ace Medical setting "Maximum Revive Time" -- Additionally, the "Seconds added to revive timer (+/- 3 seconds)" for CPR is minimum 15 seconds. 

This means that in many cases, especially with multiple people doing CPR, if there is no defib it can get people stuck in a deathless limbo revive state where CPR will keep them alive but they can never be revived due to the patient having passed the Ace Revive timer which is tied to the Maximum Time for successful CPR... which has been exceeded by seconds added to revive through CPR.

I can see a few possible ways around this...
1. Add a checkbox to decouple "Maximum time for CPR" from "Max Revive Time" so that the maximum time for CPR can be higher than Max Revive Time so that it's unlikely for players to get stuck in this CPR-Limbo. 

2. Allow the "Seconds added to revive timer" to go all the way down to 0 seconds so that CPR doesn't keep people alive beyond the point that they could be revived without a defib.

**Comment by Pergor** [comment]
1. The timer for successful CPR is a second revive timer, because every CPR action adds time to the ace max revive timer. Both values are not connected in any way. You can not run out of ace revive time, while CPR is being applied, as long as the revive timer hasn't surpassed the max time for successful CPR. If the ace revive timer has run out, people will simply die and respawn or return to lobby.
If you want to have higher values for the max cpr time (even though I suppose an hour is more than enough time for a player to look at a dark screen when not being found or helped) than the ace revive time (which does not make any sense whatsoever), set the following mission variable globally:
missionNamespace setVariable ["adv_aceCPR_maxTime",XXX];

2. The action for the CPR takes exactly 15 seconds. That's why the minimum for the setting is 15 seconds per CPR action. Added on to that is a random value betwen -3 and +3 seconds. The whole point of this is to circumvent people from dying regularly while CPR is being applied. I don't intend to offer lower values, since that's what 'vanilla' ace cpr does and would run against the concept of my mod.

**Comment by Stainess** [comment]
From the documentation... 

"To set the duration during which CPR can still be applied successfully, you can set adv_aceCPR_maxTime. (Eg. if your ace_medical_maxReviveTime is 600 seconds and you want players to only be able to resuscitate patients for 300 seconds, set it to 300. If the value is higher than ace_medical_maxReviveTime, it will revert to ace_medical_maxReviveTime) After this time in seconds only regular ACE CPR will be executed and you have to use AED or PAK to resuscitate a player (default is 1200): adv_aceCPR_maxTime = 300;"

A checkbox to disable adv_aceCPR_maxTime would be nice. 

The problem is that if your unit doesn't use AED's because it's simulating a primitive army, and it doesn't use PAK because PAK's are cancer... what do you do if you overrun the timer? People don't just die, the CPR keeps them alive but they can no longer be revived by CPR. 

It's not obvious either, there's no message or status that says "This person can no longer be revived by CPR", so if people miss the CPR-revive window they can continue to administer CPR for a couple of minutes while wondering why it isn't working. 

You know?

**Comment by Pergor** [comment]
Yes, there is a message for that case: https://github.com/Pergor/ADV_Medical/blob/master/adv_aceCPR/stringtable.xml#L26

And again: If you want to disable adv_aceCPR_maxTime, just put this in your mission:
missionNamespace setVariable ["adv_aceCPR_maxTime",(missionNamespace getVariable "ace_medical_maxReviveTime")+1];

**Comment by Stainess** [comment]
Thank you
