### ISSUE TITLE
Sometimes doing the AED defib in helicopters will boot the wounded out of it

### ISSUE THREAD

**Issue by tyl3r99** [Pergor/ADV_Medical#5]
Sometimes whilst doing the AED defib in a helicopter (rhs for example) we have seen some bodies disapear from inside the helicopter but unsure where they go.

**Comment by Pergor** [comment]
That's kind of weird, since the AED does nothing else than the CPR action. And I haven't seen someone be moved out of a vehicle with CPR. I haven't seen someone be moved out of a vehicle with the AED either, but if you say so.

I would need some further testing for that. You might want to recreate that with adv_aceCPR_diag=true;
Then share the rpt-file like so: https://gist.github.com/

Try to look out for factors that might be present everytime the problem occurs.

**Comment by tyl3r99** [comment]
sure I will have a look!!



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Pergor** [comment]
Probably... Especially in combination with rhs vehicles (who are always a bit peculiar in regards to being inside or outside of the vehicle).

**Comment by tyl3r99** [comment]
this is true, id say you can close this issue



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
