### ISSUE TITLE
Wounded stable and healthy vitals not waking up

### ISSUE THREAD

**Issue by tyl3r99** [Pergor/ADV_Medical#7]
im not 100% sure which is the possible cause, however i got to start somewhere right? 

Have you had any issues of the wounded being treated and stable (healthy heart and blood pressure / no pain etc) will not wake up from revive state. Unsure why. 

before this mod our unit used PAK's in the field but its happened twice on 2 different occasions.

using latest cpr mod dated 25/5/18 off steam workshop
using ACE/rhs mainly also your splint mod. 

BELOW ARE THE CURRENT SETTINGS OUR SERVER USES.

// ACE Medical |   |   |  
-- | -- | -- | --
force ace_medical_ai_enabledFor = 2; |   |   |  
force ace_medical_AIDamageThreshold = 0.8; |   |   |  
force ace_medical_allowLitterCreation = true; |   |   |  
force ace_medical_allowUnconsciousAnimationOnTreatment = true; |   |   |  
force ace_medical_amountOfReviveLives = -1; |   |   |  
force ace_medical_bleedingCoefficient = 1.2; |   |   |  
force ace_medical_blood_enabledFor = 2; |   |   |  
force ace_medical_consumeItem_PAK = 1; |   |   |  
force ace_medical_consumeItem_SurgicalKit = 0; |   |   |  
force ace_medical_delayUnconCaptive = 3; |   |   |  
force ace_medical_enableAdvancedWounds = true; |   |   |  
force ace_medical_enableFor = 1; |   |   |  
force ace_medical_enableOverdosing = true; |   |   |  
force ace_medical_enableRevive = 1; |   |   |  
force ace_medical_enableScreams = true; |   |   |  
force ace_medical_enableUnconsciousnessAI = 0; |   |   |  
force ace_medical_enableVehicleCrashes = true; |   |   |  
force ace_medical_healHitPointAfterAdvBandage = false; |   |   |  
force ace_medical_increaseTrainingInLocations = false; |   |   |  
force ace_medical_keepLocalSettingsSynced = true; |   |   |  
force ace_medical_level = 2; |   |   |  
force ace_medical_litterCleanUpDelay = 300; |   |   |  
force ace_medical_litterSimulationDetail = 4; |   |   |  
force ace_medical_maxReviveTime = 450; |   |   |  
force ace_medical_medicSetting = 2; |   |   |  
force ace_medical_medicSetting_basicEpi = 0; |   |   |  
force ace_medical_medicSetting_PAK = 1; |   |   |  
force ace_medical_medicSetting_SurgicalKit = 1; |   |   |  
force ace_medical_menu_allow = 1; |   |   |  
force ace_medical_menu_maxRange = 3.47594; |   |   |  
force ace_medical_menu_openAfterTreatment = true; |   |   |  
force ace_medical_menu_useMenu = 1; |   |   |  
force ace_medical_menuTypeStyle = 1; |   |   |  
force ace_medical_moveUnitsFromGroupOnUnconscious = false; |   |   |  
force ace_medical_painCoefficient = 1.2; |   |   |  
ace_medical_painEffectType = 1; |   |   |  
force ace_medical_painIsOnlySuppressed = true; |   |   |  
force ace_medical_playerDamageThreshold = 1.4; |   |   |  
force ace_medical_preventInstaDeath = true; |   |   |  
force ace_medical_remoteControlledAI = true; |   |   |  
force ace_medical_useCondition_PAK = 1; |   |   |  
force ace_medical_useCondition_SurgicalKit = 0; |   |   |  
force ace_medical_useLocation_basicEpi = 0; |   |   |  
force ace_medical_useLocation_PAK = 2; |   |   |  
force ace_medical_useLocation_SurgicalKit = 0; |   |   |  

// ADV - ACE CPR |   |  
-- | -- | --
force adv_aceCPR_addTime = 20; |   |  
force adv_aceCPR_chance_0 = 14.7059; |   |  
force adv_aceCPR_chance_1 = 15; |   |  
force adv_aceCPR_chance_2 = 14.7059; |   |  
force adv_aceCPR_chance_aed = 39.9584; |   |  
force adv_aceCPR_enable = true; |   |  
force adv_aceCPR_maxTime = 600; |   |

**Comment by Pergor** [comment]
I'm not 100% sure what the problem is. If you have a stable and healthy heart rate, you're not in revive state.

**Comment by tyl3r99** [comment]
I'm not 100% either both occasions the wounded had the heart rate of 80-85 and 120-80 or close to, blood pressure.

not in any pain but just stayed on the floor

couldn't reproduce it every time though so maybe something to keep an eye out for.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Pergor** [comment]
Nah... as long as there's a heart rate, that's hardly my problem. If there's a heart rate, the patient is not in revive state and there's no use for CPR or AED.

You might want to check the following variables on your patient if that occurs:
//These are in some way or another related to CPR:
_unit getVariable "ace_medical_inReviveState";
_unit getVariable "ace_medical_inCardiacArrest";
_unit getVariable "ace_medical_heartRate";
_unit getVariable "ace_medical_pain";
_unit getVariable "ace_medical_bloodVolume";
_unit getVariable "ace_medical_bloodPressure";
_unit getVariable "ace_medical_morphine_insystem";
_unit getVariable "ace_medical_epinephrine_insystem";

//these are related to ace_medical in general:
_unit getVariable "ace_medical_heartRateAdjustments";
_unit getVariable "ace_medical_peripheralResistance";
_unit getVariable "ace_medical_bodyPartStatus";
_unit getVariable "ace_medical_allUsedMedication";

Most of these are not regularly made public, so you might have to create a workaround for that.

**Comment by tyl3r99** [comment]
sure ok thank you fella



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by IrvingMainway** [comment]
I'm having the same issues occur, casualties with good pulse & BP, no longer in pain but unable to regain consciousness until killed by the timeout setting. Epi has no effect other than to raise heart rate. The only thing which has "worked" aside from a PAK is repeated use of the AED to first stop and then restart the casualty's heart.

One interesting observation I've had though is that nobody is going into arrest in the first place after being downed, we put multiple belts into someone who is downed and his pulse stays a steady 83 despite having a BP of 1/1.

**Comment by tyl3r99** [comment]
this is happening to us still also. more frequent if anything



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Pergor** [comment]
Without any hard data, I simply can't help you.

As I mentioned before: Test the variables above. If you provide me with their values when the problem occurs, I might be able to figure something out.

**Comment by tyl3r99** [comment]
how am i supposed to get this information on a server without a debug console fella?

**Comment by DeliciousJaffa** [comment]
> how am i supposed to get this information on a server without a debug console fella?
how is @Pergor meant to fix this without the information he needs, fella?

**Comment by tyl3r99** [comment]
I wasn't trying to be sarcastic I was being serious as I want to get you the info



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by DeliciousJaffa** [comment]
Ask the logged in server admin to log the variables

**Comment by tyl3r99** [comment]
I can be admin but how do I do this



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by DeliciousJaffa** [comment]
Look at the bugged player and run this.

```
_unit = cursorTarget;
_log = format ["inReviveState: %1 | inCardiacArrest: %2 | heartRate: %3 | pain: %4 | bloodVolume: %5 | bloodPressure: %6 | morphine_insystem: %7 | epinephrine_insystem: %8 ||| heartRateAdjustments: %9 | peripheralResistance: %10 | bodyPartStatus: %11 | allUsedMedication: %12",
    _unit getVariable "ace_medical_inReviveState",
    _unit getVariable "ace_medical_inCardiacArrest",
    _unit getVariable "ace_medical_heartRate",
    _unit getVariable "ace_medical_pain",
    _unit getVariable "ace_medical_bloodVolume",
    _unit getVariable "ace_medical_bloodPressure",
    _unit getVariable "ace_medical_morphine_insystem",
    _unit getVariable "ace_medical_epinephrine_insystem",
    _unit getVariable "ace_medical_heartRateAdjustments",
    _unit getVariable "ace_medical_peripheralResistance",
    _unit getVariable "ace_medical_bodyPartStatus",
    _unit getVariable "ace_medical_allUsedMedication"
];
diag_log _log;
hint _log;
systemChat _log;
```
Copy and paste the result from your RPT file (You can get to the folder it's in through 3DEN Editor in the "Open Log Folder" option)

**Comment by tyl3r99** [comment]
when you say look at the player and run this.

is there a command?



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Pergor** [comment]
Look at the player who's got the faulty behaviour, then enter this in the console:

`cursorTarget call {_unit = _this;
_log = format ["inReviveState: %1 | inCardiacArrest: %2 | heartRate: %3 | pain: %4 | bloodVolume: %5 | bloodPressure: %6 | morphine_insystem: %7 | epinephrine_insystem: %8 ||| heartRateAdjustments: %9 | peripheralResistance: %10 | bodyPartStatus: %11 | allUsedMedication: %12",
    _unit getVariable "ace_medical_inReviveState",
    _unit getVariable "ace_medical_inCardiacArrest",
    _unit getVariable "ace_medical_heartRate",
    _unit getVariable "ace_medical_pain",
    _unit getVariable "ace_medical_bloodVolume",
    _unit getVariable "ace_medical_bloodPressure",
    _unit getVariable "ace_medical_morphine_insystem",
    _unit getVariable "ace_medical_epinephrine_insystem",
    _unit getVariable "ace_medical_heartRateAdjustments",
    _unit getVariable "ace_medical_peripheralResistance",
    _unit getVariable "ace_medical_bodyPartStatus",
    _unit getVariable "ace_medical_allUsedMedication"
];
diag_log _log;
hint _log;
systemChat _log;
copyToClipboard _log;};`

And then hit "local exec".

And then you'll have all these variables easily readably copied to your clipboard (and hinted in many other ways). Thank you DeliciousJaffa, by the way.

**Comment by DeliciousJaffa** [comment]
@Pergor copyToClipboard only works in singleplayer/editor or if you're locally hosting a server.

**Comment by Pergor** [comment]
Oh... I didn't know that.

**Comment by IrvingMainway** [comment]
"inReviveState: true | inCardiacArrest: false | heartRate: 57.3839 | pain: 0.146806 | bloodVolume: 97.9874 | bloodPressure: [69.1102,103.847] | morphine_insystem: <null> | epinephrine_insystem: <null> ||| heartRateAdjustments: <null> | peripheralResistance: <null> | bodyPartStatus: [3.63157,0.372878,0,0,0,0] | allUsedMedication: []"

This is the state that a casualty was in after treatment. Unconscious his wounds had been patched and morphine had been administered to the point that he was no longer showing up as being in pain, not in cardiac arrest and with good blood pressure yet was unable to regain consciousness.

**Comment by Pergor** [comment]
'inReviveState: true'

That means that the patient has not been taken out of revive state. The probability for succesful CPR usage is drastically being reduced as long as there is Morphine in the system.
https://github.com/Pergor/ADV_Medical/blob/51d74ecb4f94330e272bfbd4e2bbbd838fd9ded5/adv_aceCPR/functions/fn_probability.sqf#L40

First "stabilize the patient", i.e. take him out of the revive state, and then give morphine to wake him up. Unless the message "XYZ performed CPR and stabilized the patient" or "XYZ used the Defibrillator and stabilized the patient" is being logged, there's no chance to make someone wake up.

I suppose the problem should not occur with AED usage instead of CPR. You can somewhat raise the probability of success by injecting epinephrine, but be careful not to kill your patient with too much medication.

If the problem persists, the next question might be, why there's still a heartrate being shown, even though the patient is in revive state. In revive state the heart rate should usually be either 0 or not changing. But that might be a regular problem with ACE's fnc_vitalLoop. But that is intended to propagate the heart rate.
Additionally: If the success of the CPR action or AED is being logged (i.e. the patient is 'stabilized'), what might cause the resetting of the revive state to fail.

What kind of damage is being inflicted for this problem to occur? Regular gun damage or overdose or explosion damage?

**Comment by IrvingMainway** [comment]
This was the cause with bullet damage. As far as stabilizing the patient goes that's exactly what's been done in most of these cases nobody would be attempting CPR or AED because the casualty isn't anywhere close to arrest. Not sure if its a change in how ACE is doing things now but, the way we had been able to use this in the past, if somebody went down with injuries that were not severe enough to put them into arrest/revive state, you could try to patch them and push morphine to resolve their pain issues and get them back up (assuming they'd not lost too much blood in the mean time).

As tested here casualties WILL NOT go into arrest even after being shot hundreds of times whilst down.

**Comment by DeliciousJaffa** [comment]
@IrvingMainway Mind posting the ACE Medical section of your CBA settings for reference/comparison

**Comment by Pergor** [comment]
ace_medical_inCardiacArrest can not be triggered by damage. The only thing that can trigger that is medication (too much morphine/epinephrine) or blood loss.
ace_medical_inReviveState and ace_medical_inCardiacArrest are different states. ace_medical_inReviveState is triggered as soon as a unit would usually die (from damage, blood loss, overdose or whatever): https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_setDead.sqf
ace_medical_inReviveState triggers fnc_reviveStateLoop: https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_reviveStateLoop.sqf that automatically sets heart rate to 0. Or rather it should usually do that. If it doesn't that's a problem of ACE³: https://github.com/acemod/ACE3/issues

**Comment by tyl3r99** [comment]
question is. is it ace causing this issue or cpr mod



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Pergor** [comment]
Given that ADV- ACE CPR does not in any way interfer with the way ACE³ handles the revive state (and setting the ace_medical_inReviveState-value to false instead of nil should not make a difference, although I will test it), I'm inclined to think that it's an ACE³-issue.

A unit should never have ace_medical_inReviveState and a value of ace_medical_heartRate > 0. But that's not something that ADV - ACE CPR interfers with in any way.

In a simple way this is all ADV - ACE CPR does:
'_target setVariable ["ace_medical_inReviveState",false,true];
_target setVariable ["ace_medical_inCardiacArrest",false,true];
_target setVariable ["ace_medical_heartRate",30, true];
_target setVariable ["ace_medical_bloodVolume",30, true];

_addTimeSetting = 15;	//15 is just an example. Value is taken from cba setting adv_aceCPR_addTime
_reviveStartTime = _target getVariable ["ace_medical_reviveStartTime",nil];
_timeAdded = _reviveStartTime + _addTimeSetting + (round random 6) - 3;
_target setVariable ["ace_medical_reviveStartTime", _timeAdded min CBA_missionTime];'

Everything else is basically fluff, or not setting any values. So it's very much a regular ACE³ error.

**Comment by Pergor** [comment]
I finally had the opportunity to encounter the bug myself.

Patient is showing a heart rate and is in ace_medical_inReviveState nonetheless. I'm still fairly certain it's an ACE³ bug and not an ADV - ACE CPR bug, since heart rate has been shown as stable even before any CPR action has been taken.

**Comment by tyl3r99** [comment]
ah okay are you able to maybe pass this info onto ace devs? worth an ask lol



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Pergor** [comment]
They have a free bug tracker on gitHub: https://github.com/acemod/ACE3/issues

**Comment by tyl3r99** [comment]
Is it possible to forward this whole ticket on?or copy paste the link? would that work



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Pergor** [comment]
Possible for sure. Not much chance of a fix though because of the work on the ace_medical-rewrite.

**Comment by Pergor** [comment]
I'll be overriding ACE_medical_fnc_actionCheckPulseLocal to check for ace_medical_inReviveState and hint accordingly.
